In [1]:
import numpy as np

Q1. Create a null vector of size 10 but the fifth value which is 1.

In [7]:
x = np.zeros(10,dtype=np.int8)
x[4] = 1
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

Q2. Create a vector with values ranging from 10 to 49.

In [2]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Q3. Create a 3X3 matrix ranging from 0 to 8.

In [4]:
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Q4. Find indices of non-zero elements from [1,2,0,0,4,0].

In [18]:
x = np.array([1,2,0,0,4,0])
x[np.nonzero(x)]
# x[x.astype(bool)]
# x[x !=0]

array([1, 2, 4])

Q5. Create a 10X10 array with random values and find minimum and maximum values.

In [13]:
import random
x=[]
for i in range(0,10):
    l =[]
    for j in range(0,10):
        num = random.randint(0,100)
        l.append(num)
    x.append(l)

print(x)
max_value = np.max(x)
min_value = np.min(x)
print(f'min_value:',min_value)
print(f'max_value:',max_value)

[[62, 52, 38, 35, 87, 95, 4, 60, 22, 79], [69, 47, 20, 18, 81, 77, 69, 3, 36, 6], [51, 8, 21, 34, 35, 41, 17, 36, 94, 55], [40, 8, 15, 100, 19, 58, 54, 90, 4, 27], [6, 79, 89, 76, 76, 65, 94, 53, 85, 34], [26, 98, 100, 63, 96, 43, 8, 44, 95, 91], [87, 45, 37, 99, 17, 95, 96, 57, 9, 89], [97, 19, 81, 62, 55, 60, 19, 16, 4, 96], [67, 18, 78, 76, 35, 32, 29, 54, 56, 78], [94, 22, 71, 17, 95, 66, 69, 10, 95, 79]]
min_value: 3
max_value: 100


Q6. Create a random vector of size 30 and find the mean value.

In [14]:
x = []
for i in range(0,30):
    num = random.randint(10,100)
    x.append(num)

mean_value = np.mean(x)
print(x)
print('mean value:',mean_value)

[16, 62, 90, 17, 57, 27, 21, 83, 100, 40, 44, 45, 73, 58, 59, 74, 74, 17, 93, 41, 69, 71, 34, 90, 61, 88, 52, 87, 92, 83]
mean value: 60.6
